version: '2'
services:
  db:
    image: postgres
  redis:
    image: redis:3.2-alpine
    ports:
      - '6379:6379'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/docker_test
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
